/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xA5, 0xAC, 0x70, 0x4B, 0xBF, 0x30, 0xA9, 0x47}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

#define DYNAMIC_KEYMAP_MACRO_COUNT 16
#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE   6000
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINDOWS

#define LEADER_TIMEOUT 800
#define LEADER_PER_KEY_TIMING
