VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes
SEND_STRING_ENABLE = yes

VIAL_INSECURE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
LEADER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
UNICODE_COMMON = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no       # Mouse keys

VPATH += keyboards/keychron/common
SRC += keychron_common.c
